[project]
channels = ["conda-forge"]
platforms = ["linux-64"]
name = "wahoo"

[dependencies]
python = ">=3.10,<3.11"
pydantic = ">=2.0, <3"

[pypi-dependencies]
dash = ">=2.16"
dash-pydantic-form = ">=0.8.2"
dash_mantine_components = ">=0.14.5"
dash_iconify = "*"
dash_ag_grid = ">=31"
pandas = "*"
fsspec = "*"