name: Publish to Pypi

on:
  pull_request:
    branches:
      - '**'
  push:
    tags:
      - '*.*.*'

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python based on pyproject.toml
        uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml
          cache: pip

      - name: Run Pre-commit
        uses: pre-commit/action@v3.0.0
        env:
          RUFF_FORMAT: github

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '128.0.6613.113'

      - name: Start chromedriver
        run: |
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Install Python based on pyproject.toml
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: pip

      - name: Run Tests
        run: |
          pip install --upgrade pip
          pip install .[dev] --no-cache-dir
          pytest -v tests/* --junitxml=test-reports/report.xml
        env:
          DISPLAY: :99

  publish:
    runs-on: ubuntu-latest
    needs: [pre-commit, run-tests]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python based on pyproject.toml
        uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml
          cache: pip

      - name: Install dependencies
        run: |
          pip install build twine "importlib_metadata<8"

      - name: Build and Publish package
        run: |
          python3 -m build
          twine upload dist/* -u __token__ -p ${{secrets.PYPI_TOKEN}} --non-interactive
